using System;
using System.Net.Http;
using System.Threading.Tasks;
using BareMetalWeb.Core.Delegates;
using BareMetalWeb.Core;
namespace BareMetalWeb.Core.Interfaces;

public interface IRouteHandlers
{
    ValueTask TimeRawHandler(BmwContext context);
    RouteHandlerDelegate BuildPageHandler(Action<BmwContext> configure);
    RouteHandlerDelegate BuildPageHandler(Func<BmwContext, ValueTask> configureAsync);
    RouteHandlerDelegate BuildPageHandler(Func<BmwContext, ValueTask<bool>> configureAsync, bool renderWhenTrue = true);
    ValueTask LoginHandler(BmwContext context);
    ValueTask LoginPostHandler(BmwContext context);
    ValueTask MfaChallengeHandler(BmwContext context);
    ValueTask MfaChallengePostHandler(BmwContext context);
    ValueTask RegisterHandler(BmwContext context);
    ValueTask RegisterPostHandler(BmwContext context);
    ValueTask LogoutHandler(BmwContext context);
    ValueTask LogoutPostHandler(BmwContext context);
    ValueTask SsoLoginHandler(BmwContext context);
    ValueTask SsoCallbackHandler(BmwContext context);
    ValueTask SsoLogoutHandler(BmwContext context);
    ValueTask AccountHandler(BmwContext context);
    ValueTask MfaStatusHandler(BmwContext context);
    ValueTask MfaSetupHandler(BmwContext context);
    ValueTask MfaSetupPostHandler(BmwContext context);
    ValueTask MfaResetHandler(BmwContext context);
    ValueTask MfaResetPostHandler(BmwContext context);
    ValueTask UsersListHandler(BmwContext context);
    ValueTask SetupHandler(BmwContext context);
    ValueTask SetupPostHandler(BmwContext context);
    ValueTask ReloadTemplatesHandler(BmwContext context);
    ValueTask DefaultPageHandler(BmwContext context);
    ValueTask MetricsJsonHandler(BmwContext context);
    ValueTask LogsViewerHandler(BmwContext context);
    ValueTask LogsPruneHandler(BmwContext context);
    ValueTask LogsPrunePostHandler(BmwContext context);
    ValueTask LogsDownloadHandler(BmwContext context);
    ValueTask EntityDesignerHandler(BmwContext context);
    ValueTask GalleryHandler(BmwContext context);
    ValueTask GalleryDeployPostHandler(BmwContext context);
    ValueTask WebStoreHandler(BmwContext context);
    ValueTask WebStoreInstallHandler(BmwContext context);
    ValueTask DataApiListHandler(BmwContext context);
    ValueTask DataApiImportHandler(BmwContext context);
    ValueTask DataApiGetHandler(BmwContext context);
    ValueTask DataApiPostHandler(BmwContext context);
    ValueTask DataApiPutHandler(BmwContext context);
    ValueTask DataApiPatchHandler(BmwContext context);
    ValueTask DataApiDeleteHandler(BmwContext context);
    ValueTask DataApiFileGetHandler(BmwContext context);
    ValueTask DataCommandHandler(BmwContext context);
    ValueTask DataSizingHandler(BmwContext context);
    ValueTask JobStatusHandler(BmwContext context);
    ValueTask JobsListHandler(BmwContext context);
    ValueTask CancelJobHandler(BmwContext context);
    ValueTask AdminSampleDataJsonHandler(BmwContext context);
    ValueTask AdminWipeDataJsonHandler(BmwContext context);
    ValueTask QueryPlanHistoryHandler(BmwContext context);
    ValueTask AttachmentsListHandler(BmwContext context);
    ValueTask AttachmentsUploadHandler(BmwContext context);
    ValueTask AttachmentsDownloadHandler(BmwContext context);
    ValueTask AttachmentsDeleteHandler(BmwContext context);
    ValueTask AttachmentsVersionsHandler(BmwContext context);
    ValueTask CommentsListHandler(BmwContext context);
    ValueTask CommentsAddHandler(BmwContext context);
    ValueTask CommentsEditHandler(BmwContext context);
    ValueTask CommentsDeleteHandler(BmwContext context);
    ValueTask GlobalSearchHandler(BmwContext context);
}
