using System;
using System.Collections.Concurrent;
using System.IO;
using System.Security.Cryptography;
using System.Threading.Tasks;
using BareMetalWeb.Core;
using Microsoft.AspNetCore.Http;

namespace BareMetalWeb.Host;

/// <summary>
/// Runtime CSS bundle service that loads pre-built per-theme CSS files into
/// memory at application startup and serves them as single cached responses.
///
/// Theme bundles are produced by <c>tools/download-assets.js</c>, which downloads
/// Bootstrap CSS, Bootstrap Icons CSS/font, and writes per-theme BMW CSS variable
/// files into <c>wwwroot/static/css/themes/</c>. These files are committed to the
/// repository and deployed with the application — no CDN access is required at runtime.
///
/// The <c>base.min.css</c> bundle contains Bootstrap + Bootstrap Icons (shared base).
/// Each named theme bundle (<c>light</c>, <c>dark</c>, <c>colourful</c>, <c>muted</c>,
/// <c>highviz</c>) contains only the BMW CSS custom-property overrides for that palette.
///
/// Each bundle is served at <c>/static/css/themes/{theme}.min.css</c>.
/// </summary>
public static class CssBundleService
{
    /// <summary>URL prefix under which all theme bundles are served.</summary>
    public const string ThemePathPrefix = "/static/css/themes/";

    /// <summary>
    /// The five BMW colour themes — matches the allowlist in <c>index.footer.html</c>
    /// and <c>theme-switcher.js</c>.
    /// Theme bundles must be present on disk (generated by <c>tools/download-assets.js</c>).
    /// </summary>
    public static readonly string[] DefaultThemes =
    {
        "light", "dark", "colourful", "muted", "highviz"
    };

    private sealed class BundleData
    {
        public byte[]? Bytes;
        public byte[]? BrotliBytes;
        public byte[]? GzipBytes;
        public string? ETag;
        public string LastModified = string.Empty;
    }

    // keyed by request path, e.g. "/static/css/themes/light.min.css"
    private static readonly ConcurrentDictionary<string, BundleData> _bundles =
        new(StringComparer.OrdinalIgnoreCase);

    // Maps request path → file path on disk for lazy loading
    private static readonly ConcurrentDictionary<string, string> _themePaths =
        new(StringComparer.OrdinalIgnoreCase);

    // ── Public API ────────────────────────────────────────────────────────────

    /// <summary>
    /// Discovers theme files on disk and registers their paths for lazy loading.
    /// The default theme (<c>light</c>) and the shared Bootstrap base (<c>base</c>)
    /// are loaded into memory eagerly; all other themes are loaded on first request.
    ///
    /// Theme files must have been generated by running <c>tools/download-assets.js</c>
    /// prior to deployment.
    /// </summary>
    public static void LoadAssets(string staticRoot)
    {
        var cssDir = Path.Combine(staticRoot, "css");
        DiscoverThemes(cssDir);
    }

    /// <summary>
    /// Scans <paramref name="cssDirectory"/> for a <c>themes</c> sub-directory,
    /// registers every <c>*.min.css</c> file for lazy loading, and eagerly loads
    /// the default theme (<c>light</c>) and Bootstrap base (<c>base</c>) into memory.
    /// </summary>
    public static void DiscoverThemes(string cssDirectory)
    {
        var themesDir = Path.Combine(cssDirectory, "themes");
        if (!Directory.Exists(themesDir))
            return;

        foreach (var file in Directory.EnumerateFiles(themesDir, "*.min.css"))
        {
            var fileName = Path.GetFileName(file);
            var requestPath = ThemePathPrefix + fileName;
            _themePaths[requestPath] = file;

            // Eagerly load the default theme and Bootstrap base so first page load is instant
            if (fileName.Equals("light.min.css", StringComparison.OrdinalIgnoreCase) ||
                fileName.Equals("base.min.css",  StringComparison.OrdinalIgnoreCase))
                LoadThemeFromDisk(requestPath, file);
        }
    }

    /// <summary>Returns the names of all discovered themes (without extension).</summary>
    public static System.Collections.Generic.IEnumerable<string> LoadedThemes()
    {
        foreach (var key in _themePaths.Keys)
        {
            var name = key[(ThemePathPrefix.Length)..]; // e.g. "light.min.css"
            if (name.EndsWith(".min.css", StringComparison.OrdinalIgnoreCase))
                yield return name[..^".min.css".Length];
        }
    }

    /// <summary>Returns <c>true</c> if at least one theme has been discovered.</summary>
    public static bool HasBundles => !_themePaths.IsEmpty;

    /// <summary>
    /// Attempts to serve a CSS theme bundle for the request path.
    /// Returns <c>true</c> if the path was handled (response fully written);
    /// <c>false</c> if the path is not a theme bundle path or no bundle is cached.
    /// </summary>
    public static async Task<bool> TryServeAsync(BmwContext context)
    {
        var requestPath = context.HttpRequest.Path.Value ?? string.Empty;
        if (!requestPath.StartsWith(ThemePathPrefix, StringComparison.OrdinalIgnoreCase))
            return false;

        // Lazy-load: if the theme is discovered but not yet cached, load it now
        if (!_bundles.TryGetValue(requestPath, out var bundle))
        {
            if (!_themePaths.TryGetValue(requestPath, out var filePath))
                return false;
            bundle = LoadThemeFromDisk(requestPath, filePath);
            if (bundle == null)
                return false;
        }

        if (!HttpMethods.IsGet(context.HttpRequest.Method) && !HttpMethods.IsHead(context.HttpRequest.Method))
        {
            context.Response.StatusCode = StatusCodes.Status405MethodNotAllowed;
            return true;
        }

        if (bundle.Bytes == null)
        {
            context.Response.StatusCode = StatusCodes.Status503ServiceUnavailable;
            return true;
        }

        var ifNoneMatch = context.HttpRequest.Headers.IfNoneMatch.ToString();
        if (!string.IsNullOrEmpty(ifNoneMatch) && ifNoneMatch == bundle.ETag)
        {
            context.Response.StatusCode = StatusCodes.Status304NotModified;
            return true;
        }

        context.Response.ContentType = "text/css; charset=utf-8";
        context.Response.Headers.CacheControl = "public, max-age=31536000, immutable";
        context.Response.Headers.ETag = bundle.ETag;
        context.Response.Headers.LastModified = bundle.LastModified;

        var encoding = CompressionHelper.SelectEncoding(context);
        var rawBytes = bundle.Bytes!; // confirmed non-null above
        var responseBytes = encoding switch
        {
            "br"   => bundle.BrotliBytes ?? rawBytes,
            "gzip" => bundle.GzipBytes   ?? rawBytes,
            _      => rawBytes
        };

        CompressionHelper.ApplyHeaders(context.Response, encoding);
        context.Response.ContentLength = responseBytes.Length;

        if (HttpMethods.IsGet(context.HttpRequest.Method))
            await context.WriteResponseAsync(responseBytes, context.RequestAborted);

        return true;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /// <summary>Loads a single theme CSS file from disk into the in-memory cache.</summary>
    private static BundleData? LoadThemeFromDisk(string requestPath, string filePath)
    {
        try
        {
            var bytes = File.ReadAllBytes(filePath);
            var lastWrite = File.GetLastWriteTimeUtc(filePath);
            var data = new BundleData
            {
                Bytes = bytes,
                BrotliBytes = CompressionHelper.CompressBrotli(bytes),
                GzipBytes = CompressionHelper.CompressGzip(bytes),
                LastModified = lastWrite.ToString("R"),
                ETag = $"\"{ComputeETag(bytes)}\""
            };
            _bundles[requestPath] = data;
            return data;
        }
        catch
        {
            return null;
        }
    }

    private static string ComputeETag(byte[] data)
    {
        var hash = SHA256.HashData(data);
        return Convert.ToHexString(hash)[..16].ToLowerInvariant();
    }
}
