using System;
using System.Collections.Generic;
using BareMetalWeb.Core;
using BareMetalWeb.Data;
using BareMetalWeb.Rendering.Models;
using Xunit;

namespace BareMetalWeb.Data.Tests;

public class IdGenerationTests
{
    [Fact]
    public void DefaultIdGenerator_GuidString_GeneratesValidGuid()
    {
        // Arrange
        var generator = new DefaultIdGenerator();
        var entityType = typeof(TestEntity);

        // Act
        var id1 = generator.GenerateId(entityType, IdGenerationStrategy.GuidString);
        var id2 = generator.GenerateId(entityType, IdGenerationStrategy.GuidString);

        // Assert
        Assert.NotNull(id1);
        Assert.NotNull(id2);
        Assert.Equal(32, id1.Length); // GUID without hyphens
        Assert.Equal(32, id2.Length);
        Assert.NotEqual(id1, id2); // Each GUID should be unique
        Assert.True(Guid.TryParseExact(id1, "N", out _)); // Valid GUID format
        Assert.True(Guid.TryParseExact(id2, "N", out _));
    }

    [Fact]
    public void DefaultIdGenerator_SequentialLong_GeneratesSequentialIds()
    {
        // Arrange
        var generator = new DefaultIdGenerator();
        var entityType = typeof(TestEntity);

        // Act
        var id1 = generator.GenerateId(entityType, IdGenerationStrategy.SequentialLong);
        var id2 = generator.GenerateId(entityType, IdGenerationStrategy.SequentialLong);
        var id3 = generator.GenerateId(entityType, IdGenerationStrategy.SequentialLong);

        // Assert
        Assert.True(long.TryParse(id1, out var num1));
        Assert.True(long.TryParse(id2, out var num2));
        Assert.True(long.TryParse(id3, out var num3));
        Assert.True(num2 > num1);
        Assert.True(num3 > num2);
    }

    [Fact]
    public void DefaultIdGenerator_SequentialLong_IsolatesSequencesPerType()
    {
        // Arrange
        var generator = new DefaultIdGenerator();
        var type1 = typeof(TestEntity);
        var type2 = typeof(AnotherTestEntity);

        // Act
        var type1_id1 = generator.GenerateId(type1, IdGenerationStrategy.SequentialLong);
        var type2_id1 = generator.GenerateId(type2, IdGenerationStrategy.SequentialLong);
        var type1_id2 = generator.GenerateId(type1, IdGenerationStrategy.SequentialLong);

        // Assert - Each type has its own sequence
        Assert.True(long.TryParse(type1_id1, out var t1n1));
        Assert.True(long.TryParse(type2_id1, out var t2n1));
        Assert.True(long.TryParse(type1_id2, out var t1n2));
        
        // Type 2's first ID should not affect Type 1's sequence
        Assert.Equal(t1n1 + 1, t1n2);
    }

    [Fact]
    public void ApplyAutoGeneratedIds_WithGuidStrategy_SetsIdProperty()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);

        // Assert
        Assert.NotNull(entity.Id);
        Assert.NotEmpty(entity.Id);
        Assert.Equal(32, entity.Id.Length);
        Assert.True(Guid.TryParseExact(entity.Id, "N", out _));
    }

    [Fact]
    public void ApplyAutoGeneratedIds_WithSequentialStrategy_SetsIdProperty()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithSequentialId>();
        var entity1 = new TestEntityWithSequentialId();
        var entity2 = new TestEntityWithSequentialId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithSequentialId));
        Assert.NotNull(metadata);

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity1);
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity2);

        // Assert
        Assert.NotNull(entity1.Id);
        Assert.NotNull(entity2.Id);
        Assert.True(long.TryParse(entity1.Id, out var num1));
        Assert.True(long.TryParse(entity2.Id, out var num2));
        Assert.True(num2 > num1);
    }

    [Fact]
    public void ApplyAutoGeneratedIds_AlwaysGeneratesForNewEntities()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Even though BaseDataObject sets a GUID in constructor,
        // ApplyAutoGeneratedIds will replace it with attribute-defined strategy
        var originalId = entity.Id;

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);

        // Assert
        // ID should be generated with GuidString strategy (32 chars, no hyphens)
        Assert.NotEqual(originalId, entity.Id);
        Assert.Equal(32, entity.Id.Length);
        Assert.True(Guid.TryParseExact(entity.Id, "N", out _));
    }

    [Fact]
    public void BuildFormFields_ForCreate_ShowsAutoGeneratedIdFieldAsReadOnly()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        var fields = DataScaffold.BuildFormFields(metadata, entity, forCreate: true);

        // Assert - auto-generated ID fields are shown as ReadOnly (not excluded)
        var idField = Assert.Single(fields, f => f.Name == "Id");
        Assert.Equal(FormFieldType.ReadOnly, idField.FieldType);
        Assert.Contains(fields, f => f.Name == "Name"); // Other fields should be present
    }

    [Fact]
    public void BuildFormFields_ForEdit_IncludesAutoGeneratedIdField()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId { Id = "test-id" };
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        var fields = DataScaffold.BuildFormFields(metadata, entity, forCreate: false);

        // Assert
        // The ID field is readonly by default in BaseDataObject, so it won't appear in edit forms either
        // But we're testing the auto-generation exclusion logic specifically for create forms
        Assert.Contains(fields, f => f.Name == "Name");
    }

    [Fact]
    public void ApplyValuesFromForm_SkipsAutoGeneratedIdField()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);
        
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);
        var originalId = entity.Id;

        var formValues = new Dictionary<string, string?>
        {
            ["Id"] = "user-provided-id",
            ["Name"] = "Test Name"
        };

        // Act
        var errors = DataScaffold.ApplyValuesFromForm(metadata, entity, formValues, forCreate: true);

        // Assert
        Assert.Empty(errors);
        Assert.Equal(originalId, entity.Id); // ID should not be overwritten
        Assert.Equal("Test Name", entity.Name);
    }

    // Test entities
    private class TestEntity : BaseDataObject
    {
    }

    private class AnotherTestEntity : BaseDataObject
    {
    }

    [DataEntity("TestEntitiesWithAutoId")]
    private class TestEntityWithAutoId : BaseDataObject
    {
        [IdGeneration(IdGenerationStrategy.GuidString)]
        [DataField(Order = 0, ReadOnly = true)]
        public new string Id
        {
            get => base.Id;
            set => base.Id = value;
        }

        [DataField(Label = "Name", Order = 1, Required = true)]
        public string Name { get; set; } = string.Empty;
    }

    [DataEntity("TestEntitiesWithSequentialId")]
    private class TestEntityWithSequentialId : BaseDataObject
    {
        [IdGeneration(IdGenerationStrategy.SequentialLong)]
        [DataField(Order = 0, ReadOnly = true)]
        public new string Id
        {
            get => base.Id;
            set => base.Id = value;
        }

        [DataField(Label = "Name", Order = 1, Required = true)]
        public string Name { get; set; } = string.Empty;
    }
}
