using System;
using System.Collections.Generic;
using BareMetalWeb.Core;
using BareMetalWeb.Data;
using BareMetalWeb.Rendering.Models;
using Xunit;

namespace BareMetalWeb.Data.Tests;

public class IdGenerationTests
{
    [Fact]
    public void DefaultIdGenerator_Sequential_GeneratesSequentialKeys()
    {
        // Arrange
        var generator = new DefaultIdGenerator();
        var entityType = typeof(TestEntity);

        // Act
        var key1 = generator.GenerateKey(entityType);
        var key2 = generator.GenerateKey(entityType);
        var key3 = generator.GenerateKey(entityType);

        // Assert
        Assert.True(key1 > 0);
        Assert.True(key2 > key1);
        Assert.True(key3 > key2);
    }

    [Fact]
    public void DefaultIdGenerator_Sequential_IsolatesSequencesPerType()
    {
        // Arrange
        var generator = new DefaultIdGenerator();
        var type1 = typeof(TestEntity);
        var type2 = typeof(AnotherTestEntity);

        // Act
        var type1_key1 = generator.GenerateKey(type1);
        var type2_key1 = generator.GenerateKey(type2);
        var type1_key2 = generator.GenerateKey(type1);

        // Assert - Each type has its own sequence
        Assert.True(type1_key2 > type1_key1);
        Assert.Equal(type1_key1 + 1, type1_key2);
    }

    [Fact]
    public void ApplyAutoGeneratedIds_WithSequentialStrategy_SetsKeyProperty()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);

        // Assert
        Assert.True(entity.Key > 0);
    }

    [Fact]
    public void ApplyAutoGeneratedIds_WithSequentialStrategy_GeneratesIncreasingKeys()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithSequentialId>();
        var entity1 = new TestEntityWithSequentialId();
        var entity2 = new TestEntityWithSequentialId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithSequentialId));
        Assert.NotNull(metadata);

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity1);
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity2);

        // Assert
        Assert.True(entity1.Key > 0);
        Assert.True(entity2.Key > 0);
        Assert.True(entity2.Key > entity1.Key);
    }

    [Fact]
    public void ApplyAutoGeneratedIds_AlwaysGeneratesForNewEntities()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        var originalKey = entity.Key;

        // Act
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);

        // Assert
        Assert.NotEqual(originalKey, entity.Key);
        Assert.True(entity.Key > 0);
    }

    [Fact]
    public void BuildFormFields_ForCreate_ExcludesAutoGeneratedKeyField()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        var fields = DataScaffold.BuildFormFields(metadata, entity, forCreate: true);

        // Assert - auto-generated Key fields should be excluded from create forms
        Assert.DoesNotContain(fields, f => f.Name == "Key");
        Assert.Contains(fields, f => f.Name == "Name"); // Other fields should be present
    }

    [Fact]
    public void BuildFormFields_ForEdit_IncludesAutoGeneratedKeyField()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId { Key = 42 };
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);

        // Act
        var fields = DataScaffold.BuildFormFields(metadata, entity, forCreate: false);

        // Assert
        Assert.Contains(fields, f => f.Name == "Name");
    }

    [Fact]
    public void ApplyValuesFromForm_SkipsAutoGeneratedKeyField()
    {
        // Arrange
        DataScaffold.RegisterEntity<TestEntityWithAutoId>();
        var entity = new TestEntityWithAutoId();
        var metadata = DataScaffold.GetEntityByType(typeof(TestEntityWithAutoId));
        Assert.NotNull(metadata);
        
        DataScaffold.ApplyAutoGeneratedIds(metadata, entity);
        var originalKey = entity.Key;

        var formValues = new Dictionary<string, string?>
        {
            ["Key"] = "999",
            ["Name"] = "Test Name"
        };

        // Act
        var errors = DataScaffold.ApplyValuesFromForm(metadata, entity, formValues, forCreate: true);

        // Assert
        Assert.Empty(errors);
        Assert.Equal(originalKey, entity.Key); // Key should not be overwritten
        Assert.Equal("Test Name", entity.Name);
    }

    // Test entities
    private class TestEntity : BaseDataObject
    {
    }

    private class AnotherTestEntity : BaseDataObject
    {
    }

    [DataEntity("TestEntitiesWithAutoId")]
    private class TestEntityWithAutoId : BaseDataObject
    {
        [IdGeneration(IdGenerationStrategy.Sequential)]
        [DataField(Order = 0, ReadOnly = true)]
        public new uint Key
        {
            get => base.Key;
            set => base.Key = value;
        }

        [DataField(Label = "Name", Order = 1, Required = true)]
        public string Name { get; set; } = string.Empty;
    }

    [DataEntity("TestEntitiesWithSequentialId")]
    private class TestEntityWithSequentialId : BaseDataObject
    {
        [IdGeneration(IdGenerationStrategy.Sequential)]
        [DataField(Order = 0, ReadOnly = true)]
        public new uint Key
        {
            get => base.Key;
            set => base.Key = value;
        }

        [DataField(Label = "Name", Order = 1, Required = true)]
        public string Name { get; set; } = string.Empty;
    }
}
