apiVersion: v1
kind: Service
metadata:
  name: baremetalweb-headless
  namespace: baremetalweb
  labels:
    app.kubernetes.io/name: baremetalweb
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: baremetalweb
  ports:
    - name: http
      port: 5232
      targetPort: http
      protocol: TCP
  # Each pod addressable as:
  #   baremetalweb-0.baremetalweb-headless.baremetalweb.svc.cluster.local
  #   baremetalweb-1.baremetalweb-headless.baremetalweb.svc.cluster.local
