namespace BareMetalWeb.Rendering.Models;

public sealed record FormField(
    FormFieldType FieldType,
    string Name,
    string Label,
    bool Required = false,
    string? Placeholder = null,
    string? Value = null,
    int DecimalPlaces = 2,
    string? SelectedValue = null,
    IReadOnlyList<KeyValuePair<string, string>>? LookupOptions = null,
    IReadOnlyList<string>? CurrencyOptions = null,
    IReadOnlyList<KeyValuePair<string, string>>? CountryOptions = null,
    string? EmailPattern = null,
    string? ButtonType = null,
    string? ButtonStyle = null,
    string? ButtonText = null,
    string? LinkUrl = null,
    string? LinkText = null,
    string? LinkTarget = null,
    string? LinkClass = null,
    string? Html = null,
    string? LookupTargetType = null,
    string? LookupTargetSlug = null,
    bool IsHighCardinality = false,
    string? LookupDisplayValue = null,
    string? LookupSearchField = null,
    string? LookupValueField = null,
    bool IsComputed = false,
    string? ComputedStrategy = null,
    string? Accept = null,
    long? MaxFileSizeBytes = null,
    string? ExistingFileName = null,
    string? ExistingFileUrl = null,
    bool IsCalculated = false,
    string? CalculatedExpression = null,
    string? DisplayFormat = null,
    int? MinLength = null,
    int? MaxLength = null,
    double? RangeMin = null,
    double? RangeMax = null,
    string? Pattern = null,
    string? ValidationError = null,
    string? ValidationRulesJson = null
);
