namespace BareMetalWeb.Host;

public readonly record struct MetricsSnapshot(
    long TotalRequests,
    long ErrorRequests,
    TimeSpan AverageResponseTime,
    TimeSpan RecentMinimumResponseTime,
    TimeSpan RecentMaximumResponseTime,
    TimeSpan RecentAverageResponseTime,
    TimeSpan RecentP95ResponseTime,
    TimeSpan RecentP99ResponseTime,
    TimeSpan Recent10sAverageResponseTime,
    long Requests2xx,
    long Requests4xx,
    long Requests5xx,
    long RequestsOther,
    long ThrottledRequests,
    long RequestsInFlight,
    int ProcessId,
    long WorkingSet64,
    long VirtualMemorySize64,
    TimeSpan ProcessUptime,
    long RouteDispatchCount,
    TimeSpan RouteDispatchAverage,
    long WalReadCount,
    TimeSpan WalReadAverage,
    long UiRenderCount,
    TimeSpan UiRenderAverage,
    long SerializationCount,
    TimeSpan SerializationAverage,
    int GcGen0Collections,
    int GcGen1Collections,
    int GcGen2Collections,
    long GcTotalAllocatedBytes
);
